# Generated by Django 5.2.5 on 2025-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de barras'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('barcode',)},
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('venta_precio__gt', models.F('coste_precio'))), name='precio_venta_mayor_coste'),
        ),
    ]
