# Generated by Django 5.2.5 on 2025-09-02 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='inventariomovimiento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='stock_no_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='precio_venta_mayor_coste',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__nombre_f5539a_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__categor_32aa4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__is_acti_2a9a5a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='movimiento_tipo',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste')], max_length=3),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia_codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='coste_precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='localizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='max_stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='venta_precio',
        ),
    ]
