# Generated by Django 5.2.5 on 2025-09-03 14:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_categoria_options_alter_producto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariomovimiento',
            name='operation_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='performed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='coste_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='max_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='min_stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='venta_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='inventariomovimiento',
            index=models.Index(fields=['producto', 'created_at'], name='inventario__product_24ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariomovimiento',
            index=models.Index(fields=['movimiento_tipo'], name='inventario__movimie_7ecc79_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='categoria_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='producto_min_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('max_stock__isnull', True), ('max_stock__gte', models.F('min_stock')), _connector='OR'), name='producto_max_ge_min_or_null'),
        ),
    ]
